name:                LearnFluidMechanics
version:             0.1.0.0
github:              "eklinkhammer/LearnFluidMechanics"
license:             BSD3
author:              "Eric Klinkhammer"
maintainer:          "eklinkhammer@gmail.com"
copyright:           "2020 Eric Klinkhammer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eklinkhammer/LearnFluidMechanics#readme>

dependencies:
- base >= 4.7 && < 5
- dimensional >= 1.3

library:
  source-dirs: src

executables:
  LearnFluidMechanics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LearnFluidMechanics

tests:
  LearnFluidMechanics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LearnFluidMechanics
